  - name: creates openhim scripts directory
    file: path=/etc/openhim-setup state=directory
    tags: openhim-setup

  - name: copy load-data script to server
    template: src=load-initial-data.sh.j2 dest=/etc/openhim-setup/load-initial-data.sh mode=0755
    tags: openhim-setup

  - name: copy data file to server
    template: src=openhim-config.json.j2 dest=/etc/openhim-setup/openhim-config.json
    tags: openhim-setup

  - name: install jq for json data processing
    get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      dest: /usr/bin/jq
      mode: 755
    tags: openhim-setup

  - name: load inital data for openhim (only executed on first run)
    command: /etc/openhim-setup/load-initial-data.sh
    args:
      creates: /etc/openhim-setup/load-initial-data.sh_already-ran
    tags: openhim-setup